version: '3.8'

volumes:
  cache_data:
    driver: local
  db_data:
    driver: local

services:
  cache:
    image: redis
    container_name: 'forum-cache'
    ports:
      - 6379:6379
    volumes:
      - 'cache_data:/data'

  database:
    image: bitnami/postgresql:15
    container_name: 'forum-pg'
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRESQL_USERNAME: docker
      POSTGRESQL_PASSWORD: docker
      POSTGRESQL_DATABASE: forum
    volumes:
      - 'db_data:/bitnami/postgresql'

  # dev:
  #   build: .
  #   container_name: 'forum-api'
  #   ports:
  #     - 3000:3000
  #   depends_on:
  #     - database
  #   volumes:
  #     - .:/usr/app

